// examples/angular/src/app/data-grid.component.ts
import {
  Component,
  ViewEncapsulation,
  CUSTOM_ELEMENTS_SCHEMA,
} from '@angular/core';
import { PredefinedMenuItemKey } from 'handsontable/plugins/contextMenu';
import { HotTableComponent } from '@handsontable/angular-wrapper';

import { getData } from './utils/constants';
import { alignHeaders, addClassesToRows } from './utils/hooks-callbacks';

@Component({
  encapsulation: ViewEncapsulation.None,
  selector: 'data-grid',
  standalone: true,
  templateUrl: './data-grid.component.html',
  //styleUrls: ['./data-grid.scss'],
  imports: [HotTableComponent],
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
})
export class DataGridComponent {
  initialData = getData();
  gridSettings = {
    height: 450,
    colWidths: [180, 220, 140, 120, 120, 120, 140],
    colHeaders: [
      'Company Name',
      'Name',
      'Sell date',
      'In stock',
      'Quantity',
      'Order ID',
      'Country',
    ],
    contextMenu: [
      'cut',
      'copy',
      '---------',
      'row_above',
      'row_below',
      'remove_row',
      '---------',
      'alignment',
      'make_read_only',
      'clear_column',
    ] as PredefinedMenuItemKey[],
    dropdownMenu: true,
    hiddenColumns: {
      indicators: true,
    },
    multiColumnSorting: true,
    filters: true,
    rowHeaders: true,
    headerClassName: 'htLeft',
    beforeRenderer: addClassesToRows,
    manualRowMove: true,
    autoWrapRow: true,
    autoWrapCol: true,
    autoRowSize: true,
    manualRowResize: true,
    manualColumnResize: true,
    navigableHeaders: true,
    imeFastEdit: true,
    columns: [
      { data: 1 },
      { data: 3 },
      {
        data: 4,
        type: 'date',
        dateFormat: {
          day: '2-digit',
          month: '2-digit',
          year: 'numeric',
        },
        locale: 'en-GB',
        allowInvalid: false,
      },
      { data: 6, type: 'checkbox', className: 'htCenter' },
      { data: 7, type: 'numeric' },
      { data: 5 },
      { data: 2 },
    ],
    themeName: 'ht-theme-main',
    licenseKey: 'non-commercial-and-evaluation',
  };
}

// examples/vue/src/components/DataGrid.vue
<script lang="ts">
import { defineComponent } from 'vue';
import { HotTable, HotColumn } from '@handsontable/vue3';
import { registerAllModules } from 'handsontable/registry';
import 'handsontable/styles/handsontable.min.css';
import 'handsontable/styles/ht-theme-main.min.css';

import { data } from '../constants';

import { alignHeaders, addClassesToRows } from '../hooks-callbacks';

// register Handsontable's modules
registerAllModules();

export default defineComponent({
  name: 'DataGrid',
  components: {
    HotTable,
    HotColumn,
  },
  computed: {
    alignHeadersProp() {
      return alignHeaders;
    },

    addClassesToRowsProp() {
      return addClassesToRows;
    },

    dataProp() {
      return data;
    },
  },
});
</script>

<template>
  <div id="example" class="ht-theme-main">
    <HotTable
      :data="dataProp"
      :height="450"
      :colWidths="[170, 222, 130, 120, 120, 140, 156]"
      :colHeaders="[
        'Company name',
        'Name',
        'Sell date',
        'In stock',
        'Qty',
        'Order ID',
        'Country',
      ]"
      :dropdownMenu="true"
      :hiddenColumns="{
        indicators: true,
      }"
      :contextMenu="true"
      :multiColumnSorting="true"
      :filters="true"
      :rowHeaders="true"
      :afterGetColHeader="alignHeadersProp"
      :beforeRenderer="addClassesToRowsProp"
      :manualRowMove="true"
      :autoWrapRow="true"
      :autoWrapCol="true"
      licenseKey="non-commercial-and-evaluation"
    >
      <HotColumn data="companyName" />
      <HotColumn data="name" />
      <HotColumn data="sellDate" type="date" :allowInvalid="false" />
      <HotColumn data="inStock" type="checkbox" className="htCenter" />
      <HotColumn data="quantity" type="numeric" />
      <HotColumn data="orderId" />
      <HotColumn data="country" />
    </HotTable>
  </div>
</template>

<style lang="css">
/*
  A stylesheet customizing app (custom renderers)
*/

table.htCore tr.odd td {
  background: #fafbff;
}

/*
  A stylesheet customizing Handsontable style
*/

.handsontable {
  font-size: 13px;
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', 'Roboto', 'Oxygen',
    'Ubuntu', 'Helvetica Neue', Arial, sans-serif;
  font-weight: 400;
}

.handsontable .collapsibleIndicator {
  text-align: center;
}

td .error {
  background: #ff4c42;
}
</style>
